### ISSUE TITLE
Verify tab cannot open

### ISSUE THREAD

**Issue by Cyber-Spectre** [ImY0mu/hub-webapp-dist#1]
Whenever you are prompted to verify you aren't a bot, clicking the button doesn't open a new tab leading to the verification, instead you need to go to the actual website or mobile build to verify.

**Comment by ImY0mu** [comment]
Thank you for the report. There are not many users of web client so I am happy to hear some feedback from you guys. 

I will look into it on Monday.

Cheers,
Y0mu

**Comment by ImY0mu** [comment]
Should be fixed.
