### ISSUE TITLE
Player Health Displays Improperly Against World Bosses

### ISSUE THREAD

**Issue by Cyber-Spectre** [ImY0mu/hub-webapp-dist#2]
Found another one for you, everytime I fight a world boss on the web client, my health bar doesn't display right, my health value stays the same but the actual bar still shrinks as I take damage. I waited a bit before reporting this to see if I noticed this when fighting anything else but I've only noticed it with world bosses.

**Comment by ImY0mu** [comment]
Does it happen in web app as well or no?

**Comment by Cyber-Spectre** [comment]
> Does it happen in web app as well or no?

Not sure, next time I am able to fight a world boss on PC I'll do it on the web app to see
| Just checked, and it's an issue with the website as well
